name: Run Unit Test

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install uv
        uv pip install --system --no-build-isolation torch==2.1.2
        uv pip install --system --no-build-isolation -e .

    - name: Lint with Ruff
      run: |
        uv pip install --system ruff
        ruff check .

    - name: Run tests
      run: |
        python -m unittest discover -s tests